apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
    - name: success-rate
      successCondition: result.successRate >= 0.95
      provider:
        newRelic:
          profile: my-newrelic-secret  # optional, defaults to 'newrelic'
          query: |
            FROM Transaction SELECT percentage(count(*), WHERE httpResponseCode != 500) as successRate where appName = 'test'
