apiVersion: batch/v1
kind: Job
metadata:
  name: job-callback-failure-job
  annotations:
    argocd.argoproj.io/hook: SyncFail
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: job-callback-failure
          image: nginx:1.15.4
          command: ["sleep", "15"]
          env:
            - name: CI_PROJECT_ID
              value: test
      restartPolicy: Never
  backoffLimit: 0
