apiVersion: batch/v1
kind: Job
metadata:
  name: job-callback-success-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: job-callback-success
          image: nginx:1.15.4
          command: ["sleep", "3600"]
          env:
            - name: CI_PROJECT_ID
              value: test
      restartPolicy: Never
  backoffLimit: 0
